openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: localhost
    url: http://localhost:3002/api
info:
  description: Cloud TP1
  version: "1.0.0"
  title: Cloud TP1
  contact:
    email: nocompany@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: books
    description: API pour mes bouquins
paths:
  /book:
    get:
      tags:
        - books
      summary: récupère tous les livres
      operationId: searchAll
      description: récupère tous les livres
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      tags:
        - books
      summary: Crée un livres
      operationId: createBook
      description: Crée un livre
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookForCreate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /book/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the book to get
      tags:
        - books
      summary: récupère un livre
      operationId: searchOne
      description: récupère un livre
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookForCreate'
        '404':
          description: Not found
components:
  schemas:  
    BookForCreate:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
          example: Lord of the ring
        description:
          type: string
          example: Somebody lost his rings
    Book:
      type: object
      allOf:
        - $ref: '#/components/schemas/BookForCreate'
      required:
        - id
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: id
          example: 42
        createdAt:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        updatedAt:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'